name: labDevOps pipeline
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  build: 
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v1
     name: Analizamos el proyecto
   - name: Ejecutamos un comando
     run: echo Esta ejecutando el pipeline
   - name: Ejecutamos varias Lineas
     run :
       echo varias Lineas

    
       ls -la
   - name: Run linter on pull request 
     run: echo Running linter
